### ISSUE TITLE
SS solution with random rates

### ISSUE THREAD

**Issue by charlesm93** [metrumresearchgroup/math#10]
#### Summary:
Overload SS functions for general and mix models to handle case where rate is passed as a vector of parameters.

#### Description:
The numerical integrator and algebra solver require we specify very clearly which arguments are parameters and which ones fixed data. The pred functions need to be carefully overloaded to distinguish case where rate is fixed or random.

#### Current Version:
Torsten v0.83
Stan v2.16.0

**Comment by yizhang-yiz** [comment]
Addressed in https://github.com/metrumresearchgroup/math/pull/31
