### ISSUE TITLE
Gradient Tests with Rates

### ISSUE THREAD

**Issue by charlesm93** [metrumresearchgroup/math#11]
#### Summary:
So far gradient tests have focused on three arguments: `pMatrix`, `biovar`, and `tlag`, and have tested the so-called vdd, dvd, and ddv regime. This needs to be expanded to test combinations of regimes.

Furthermore, we want to test event arguments, which might be pass as parameters, in particular `amt` and `rate`. These seem to be causing errors.

#### Description:
The unit tests handle the case where amt and rate are modified well. I implemented a test for rates, and got errors. In generalOdeModel, all the gradients w.r.t rates went to 0.

In the case of PKModelOneCpt, the gradients were properly evaluated -- and at times non-zero--, except at one event.

#### Reproducible Steps:
See unit tests on branch issue-51-SS-rate.

#### Current Output:
Gradients are NOT properly evaluated at all events.

#### Expected Output:
Autodiff agrees with finite diff, at least in the case where rate != 0 (else, we run into a deeper problem which involves conditional statements, and which certainly needs to be fixed at some point).

#### Current Version:
Torsten v0.83
Stan v2.16

**Comment by charlesm93** [comment]
I've dug further into the gradient test for PKModelOneCpt. The error occurs at events that coincide with the end of an infusion time. I believe finite diff is at fault here.

This has to do with the `MakeRates()` function in the RateHistory class. Recall the RateHistory object contains one Rate object for each _unique_ time of the event schedule. Consider a dosing event, which corresponds to an infusion with rate _R_, ending after _delta_ units of time. At the end of an infusion time, either a new Rate is created or the Rate occurring at the end of that infusion time gets updated. All rates in RateHistory get updated, by adding _R_ to the right compartment at times t0 < t < t0 + delta. The rate at the end of the infusion time stays at 0.

If no event coincides with the end of the infusion time, no problem.

If such an event already exists, then, with autodiff, the rate t0 + delta is 0. With finite diff, we have for the lower bound rate:
R' = R - d
=> delta' = amt / (R - d)
=> delta' > delta
=> the rate at the end of the infusion time is augmented with R, instead of staying at 0. Hence the difference.

**Comment by yizhang-yiz** [comment]
Done in 0.87.
