### ISSUE TITLE
fail to build multiple_translation_units_test

### ISSUE THREAD

**Issue by yizhang-yiz** [metrumresearchgroup/math#18]
#### Summary:
Not able to build multiple_translation_units_test on torsten-master branch

#### Description:
> $ make -j1 test/unit/multiple_translation_units_test
duplicate symbol _marker_count in:
    test/unit/multiple_translation_units1.o
    test/unit/multiple_translation_units2.o
ld: 1 duplicate symbol for architecture x86_64
> 

#### Reproducible Steps:
> make -j1 test/unit/multiple_translation_units_test

#### Current Output:
> duplicate symbol _marker_count in:
    test/unit/multiple_translation_units1.o
    test/unit/multiple_translation_units2.o
ld: 1 duplicate symbol for architecture x86_64

#### Expected Output:
No ld error.

#### Current Version:
v2.16.0

**Comment by charlesm93** [comment]
I sparsely used the marker() function to do some debugging but I moved to better methods a while ago. Removing it is a good idea, especially since it causes issues.

**Comment by yizhang-yiz** [comment]
Yeah that's essentially how the fix is about.
