### ISSUE TITLE
Unit tests for event arguments as parameters

### ISSUE THREAD

**Issue by charlesm93** [metrumresearchgroup/math#4]
#### Summary:
The unit tests currently focus on the parameters in theta, biovar, and tlag. The _event_ arguments can also be passed as parameters (as long as they are continuous) and we need unit tests to make sure the parameters are properly handled.

#### Description:
The _event_ arguments: time, amt, rate, and ii can be passed as parameters and need to be tested.

I probably need to tweak generalOdeModel_* since it currently coerces rate to data and passes it as the x_real argument of the ODE integrator. Instead it should get passed in the parm argument, if (and only if) rate is an array of parameters.

#### Current Output:
Unsure: what happens if rate is passed in as parameters in generalOdeModel_* ?
What happens when Stan computes the AD w.r.t time, when we deal with a discontinuity such as a bolus dosing? 

#### Expected Output:
Want torsten to accurately and efficiently handle parameters.

#### Current Version:
Stan v2.14.0
Torsten v0.82

**Comment by yizhang-yiz** [comment]
Implemented in 0.87.
