### ISSUE TITLE
Integral with parameter upper-bound

### ISSUE THREAD

**Issue by charlesm93** [metrumresearchgroup/math#8]
#### Summary:
Sometimes the upper-bound of an integral is a parameter. For instance, in the SS case, delta, the duration of the infusion time, can be a parameter. The ODE integrator does not handle this case, but we can get a solution by doing a variable transformation.

#### Current Output:
Throws an exception when amt, and therefore delta is a parameter.

#### Expected Output:
Finds SS solution and computes gradients.

#### Current Version:
Stan v2.15.0
Torsten v0.83-beta

**Comment by yizhang-yiz** [comment]
I'm closing this as the 1d integrator has this capability.
